version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: fullstack-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Welcome#$4321
      MYSQL_DATABASE: fullStackDemo
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - fullstack-network
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pWelcome#$4321", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./FullStackDemo-Backend
    container_name: fullstack-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fullStackDemo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Welcome#$4321
      APP_JWT_SECRET: d9f3c7e4b8a2f1c9e0a4b7d8c2e9f6a1b3d5e7f8a9c0b1d2e3f4a5b6c7d8e9
      APP_JWT_EXPIRATION_MS: 86400000

    ports:
      - "8080:8080"
    networks:
      - fullstack-network
    restart: always

  frontend:
    build: ./FullStackDemo-Frontend
    container_name: fullstack-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - fullstack-network
    restart: always

networks:
  fullstack-network:
    driver: bridge

volumes:
  mysql_data: